INSERT INTO Produits VALUES('Bulbes','../img/bulbes_begonia.jpg','b01','3 bulbes de bégonias',5,10);
INSERT INTO Produits VALUES('Bulbes','../img/bulbes_dahlia.jpg','b02','10 bulbes de dahlias',12,10);
INSERT INTO Produits VALUES('Bulbes','../img/bulbes_glaieul.jpg','b03','50 glaïeuls',9,10);
INSERT INTO Produits VALUES('Rosiers','../img/rosiers_gdefleur.jpg','r01','1 pied spécial grandes fleurs',20,10);
INSERT INTO Produits VALUES('Rosiers','../img/rosiers_parfum.jpg','r02','Une variété sélectionné pour son parfum',9,10);
INSERT INTO Produits VALUES('Rosiers','../img/rosiers_arbuste.jpg','r03','Rosier arbuste',8,10);
INSERT INTO Produits VALUES('Plantes à Massif','../img/massif_marguerite.jpg','m01','Lot de 3 marguerites',5,10);
INSERT INTO Produits VALUES('Plantes à Massif','../img/massif_pensee.jpg','m02','Pour un bouquet de 6 pensées',6,10);
INSERT INTO Produits VALUES('Plantes à Massif','../img/massif_melange.jpg','m03','Mélange varié de 10 plantes à massif',15,10);
INSERT INTO Produits VALUES('Voltaire','../img/Voltaire.png','v01','Bot pour Voltaire',100,0);
INSERT INTO Users VALUES('Homme','Mignot','Célian','2001-03-30','mignotceli@cy-tech.fr','Cytech0001!',0);
